config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  resources :tags
  devise_for :users
  get 'events/index'
  root to: "events#index"
  resources :events do
    resources :orders, only: [:index, :create]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_one :order

  has_many :event_tags, dependent: :destroy  #中間テーブル
  has_many :tags, through: :event_tags  #tagのアソシエーション

  validates :concept, presence: true
  validates :place, presence: true
  validates :period, presence: true
  validates :image, presence: true
end

app/models/event_tag.rb
class EventTag < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_one    :address
end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :post_code, :prefecture_id, :city, :street, :building_name, :phone_number, :item_id, :user_id
  with_options presence: true do
    validates :post_code, format: { with: /\A\d{3}[-]\d{4}\z/ }
    validates :phone_number, format: { with: /\A\d{11}\z/ }
    validates :prefecture_id
    validates :city
    validates :street
    validates :prefecture_id, numericality: { other_than: 0 }
  end

  def save
    order = Event.create(event_id: item_id, user_id: user_id)
    Address.create(post_code: post_code, prefecture_id: prefecture_id, city: city, phone_number: phone_number, street: street, order_id: order.id)
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 0, name: '--' },
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :event_tags, dependent: :destroy
  has_many :events, through: :event_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  has_many :events, dependent: :destroy
  has_many :orders
end

#バリデーション 設置

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])

  end

  def edit
    @event = Event.find(params[:id])
    unless current_user.id == @event.user.id
      redirect_to action: :index 
    end 
  end

  def update
    if event = Event.find(params[:id])
      event.update(event_params)
      redirect_to event_path (event.id), method: :get
    else
      render 'edit'
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:concept, :place, :period, :image, tag_ids: []).merge(user_id: current_user.id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @order_address = OrderAddress.new
    @event = Event.find(params[:event_id])
  end
  
  def create
  end

  private

  def event_params
    params.require(:event_address).permit(:post_code, :prefecture_id, :city, :street, :building_name, :phone_number, :order).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
      @tags = Tag.find(1)
      @tagss = Tag.find(20)
      @tagsss = Tag.find(21)
      @tagssss = Tag.find(22)
  end

  def show
    @tag = Tag.find(params[:id])
    @event = Event.new
    @events = @tag.events
  end

  private

  def event_params
    params.require(:event).permit(:concept, :place, :period, :image, tag_ids: []).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/events/_event.html.erb
<div class="card">
  <div class="card__body">
  <div class="event-images">
  <%= link_to image_tag(event.image, class: :class__img), event_path(event.id), method: :get %>
  </div>
  <%#= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype.id), method: :get %>
  <p class="card__summary">
    <%= event.concept %>
    <%= event.place %>
    <%= event.period%>
    <%= link_to " 【Eventer by#{event.user.nickname}】",class: :card__user %>
  </p>
  </div>
</div>

app/views/events/_form.html.erb
event#form

     <div>
       <%= tag.label do %>
         <%= tag.check_box %>
         <%= tag.text %>
       <% end %>

    <%= form.text_area %>

app/views/events/_map.html.erb
<style>
#map {
  height: 600px;
  width: 800px;
}
</style>

<div id='map'></div>

<script>
  let map

    function initMap(){
      geocoder = new google.maps.Geocoder()

      map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 35.68123620000001, lng:139.7671248},
          zoom: 12,
      });
      }
</script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap"></script>

app/views/events/edit.html.erb
<%= form_with(model: @event, local: true) do |f| %>
  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_field :concept %>
  </div>

  <div class="field">
    <%= f.label :place, "場所" %><br />
    <%= f.text_area :place, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :period, "期間" %><br />
    <%= f.text_area :period, class: :form__text %>
  </div>
<!--
  <div class="field">
    <%= f.label :food, "食材" %><br />
    <%= f.text_area :food, class: :form__text %>
  </div>

   <div class="field">
    <%= f.label :fee, "参加費" %><br />
    <%= f.text_area :fee, class: :form__text%>
  </div>

   <div class="field">
    <%= f.label :people, "参加人数" %><br />
    <%= f.text_area :people, class: :form__text %>
  </div>    
     -->
  
     <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>

<% end %>

app/views/events/index.html.erb
<header>
<div class="header-title">
<h1>Camp Crew </h1>
</div>
  <div class="header-menu">
    <div class="header-title">
    <h1></h1>
    </div>
</header>
<div class="all-ground">
  <div class="header-info">
      <ul class='lists-right'>
        <% if user_signed_in? %>
       <div class="user-desc">
        <div class="user-name">
          <li><%= link_to "こんにちは#{current_user.nickname}さん", root_path, class: "user-nickname" %></li>
        </div>
        <div class="header-menus">
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"%></li>
          <li><%= link_to '投稿する', new_event_path, class: "sign-up" %></li>
          <li><%= link_to '地図から探す', root_path, class: "sign-up" %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
        <% end %>
         


      <div class="whach">
       <script>
           var today = new Date();
           var todayHtml = today.getFullYear()+'/' +(today.getMonth() +1 ) + '/' + today.getDate();

           document.write('<p class="date">' + todayHtml + '</p>');
       </script>
    </div>
  <!--
  <div class="navbar">
    <ul class="nav-lists">
      <li class="list-status">
        現在のリスト；
        <span id="current-list">選択されていません</span>
      </li>
      <li class="background-red" id="lists">リスト
      </li>
      <li>カリキュラム変更</li>
    </ul>
    <ul class="show-lists hidden" id="pull-down">
      <li class="pull-down-list">リスト1</li>
      <li class="pull-down-list">リスト2</li>
      <li class="pull-down-list">リスト3</li>
      <li class="pull-down-list">リスト4</li>
    </ul>
  </div>
-->



        </div>
      </div>
      </ul>
    </div>
  </div>

<div class="g-map">
<div id="target"></div>
</div>


<!--google-map-->




<div class="main">
<div class="contener-main">
<h2></h2>
<div class="g-map">

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="Encode" onclick="codeAddress()">
<div id="display"></div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 800px;
}
</style>

<script>
let map
let geocoder
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.6603, lng:139.7051},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 35.6603, lng:139.7051},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap"></script>
</div>


<!--google-map-->




  <div class="event-lists">
    <h1>イベント一覧 </h1>
    <div class="event-title"> 
      <%= render partial: "event", collection: @events %>
    </div>
      <div class="event">
        <h3>イベント写真</h3>
      </div>
      <div class="event">
      <h3>コンセプト</h3>
      </div>
      <div class="event">
      <h3>企画者</h3>
      </div>
  </div>
</div>



<div class="genre-item">
  <div class="past-log">
    <h1>ジャンルから選ぶ</h1>
  </div>
  <div class="genre-images">
    <div class="genre-image">
      <%= link_to image_tag("tent.png", class:"genre-btn"),  :tags %>
      <h2>オートキャンプ</h2>
    </div>
    <div class="genre-image">
      <%= link_to image_tag("fire.png", class:"genre-btn"), :tags %>
      <h2>アクティビティ</h2>
    </div>
    <div class="genre-image">
      <%= link_to image_tag("campfire.png", class:"genre-btn"), :tags %>
      <h2>料理にこだわる</h2>
     </div>
  </div>
</div>


<div class="past-log">
<h1>過去の開催模様</h1>
</div>

  <div class="card__wrapper">
    <%= render partial: "event", collection: @events %>
  </div>
</main>
</div>

app/views/events/map.html.erb
<!--google-map-->




<div class="main">
<div class="contener-main">
<h2></h2>
<div class="g-map">

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="Encode" onclick="codeAddress()">
<div id="display"></div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 800px;
}
</style>

<script>
let map
let geocoder
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.6603, lng:139.7051},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 35.6603, lng:139.7051},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap"></script>
</div>


<!--google-map-->

app/views/events/maps.html.erb
<!--google-map-->




<div class="main">
<div class="contener-main">
<h2></h2>
<div class="g-map">

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="Encode" onclick="codeAddress()">
<div id="display"></div>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 800px;
}
</style>

<script>
let map
let geocoder
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.6603, lng:139.7051},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 35.6603, lng:139.7051},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap"></script>
</div>


<!--google-map-->

app/views/events/new.html.erb
<%= form_with(model: @event, local: true) do |f| %>
  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_field :concept %>
  </div>

  <div class="field">
    <%= f.label :place, "場所" %><br />
    <%= f.text_area :place, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :period, "期間" %><br />
    <%= f.text_area :period, class: :form__text %>
  </div>
<!--
  <div class="field">
    <%= f.label :food, "食材" %><br />
    <%= f.text_area :food, class: :form__text %>
  </div>

   <div class="field">
    <%= f.label :fee, "参加費" %><br />
    <%= f.text_area :fee, class: :form__text%>
  </div>

   <div class="field">
    <%= f.label :people, "参加人数" %><br />
    <%= f.text_area :people, class: :form__text %>
  </div>    
     -->
  
     <div class="field">
    <%= f.label :image, "画像" %><br/>
    <%= f.file_field :image %>
  </div>

<div class="check_box">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
     <div>
       <%= tag.label do %>
         <%= tag.check_box %>
         <%= tag.text %>
       <% end %>
     </div>
     <% end %>
     </div>
  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>

<% end %>

app/views/events/show.html.erb
<div class="all-ground">
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @event.concept %>
      </p> 
      
      <div class="prototype__image">
        <%= image_tag @event.image %>
      </div>

      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @event.place %>
          </p>
        </div>

        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @event.period %>

            <p class="detail__title">イベントタグ</p>
            <% @event.tags.each do |tag| %>
            <%= tag.name %>
            <% end %>
          </p>
        </div>
        <div class="map-mini">
           <p class="detail__title">場所の詳細</p>
            <%= render partial: "map" %>
        </div>
      </div>
        <% if user_signed_in? && current_user.id == @event.user_id %>
          <%= link_to @event.user.nickname , root_path, class: :prototype__user %>
        <div class="prototype__manage">
          <%= link_to "編集する",  edit_event_path, class: :prototype__btn %>
          <%= link_to "削除する",  event_path, method: :delete, class: :prototype__btn %>
        </div>
        <% elsif  %>
          <%= link_to 'イベント参加ページに進む', event_orders_path(@event.id) ,class: :prototype__btn %>
        <% end %>
    </div>
  </div>
</main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampCommunity2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
 <!--   <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap"></script>  -->
  </body>
</html>

app/views/orders/index.html.erb
<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      参加内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @event.image, class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @event.concept %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= %></p>
          <p class='item-price-sub-text'>（税込）送料込み</p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>
    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= @event.place %>
      </p>
    </div>
    <%# /支払額の表示 %>
    <%= form_with model: @order_address, url: root_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>

        <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :number, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :cvc,class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
    <%# /カード情報の入力 %>
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :post_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %> 
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :street, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :building_name, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <%# /配送先の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>

app/views/tags/index.html.erb
<div class="genre-item">
  <div class="past-log">
    <h1>ジャンルから選ぶ</h1>
  </div>
  <div class="genre-images">
    <div class="genre-image">
      <%= link_to image_tag("tent.png", class:"genre-btn"),  @tagss %>
      <h2>オートキャンプ</h2>
    </div>
    <div class="genre-image">
      <%= link_to image_tag("fire.png", class:"genre-btn"), @tagsss %>
      <h2>アクティビティ</h2>
    </div>
    <div class="genre-image">
      <%= link_to image_tag("campfire.png", class:"genre-btn"), @tagssss %>
      <h2>料理にこだわる</h2>
     </div>
         <div class="genre-image">
      <%= link_to image_tag("campfire.png", class:"genre-btn"), @tags %>
      <h2>その他</h2>
  </div>
</div>

app/views/tags/show.html.erb
  <% @events.each do |event| %>

  <div class="card">
  <div class="card__body">
  <%= link_to image_tag(event.image, class: :class__img), event_path(event.id), method: :get %>
  <%#= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype.id), method: :get %>
  <p class="card__summary">
    <%= event.concept %>
    <%= event.place %>
    <%= event.period %>
    <%= link_to " 【Eventer by#{event.user.nickname}】",class: :card__user %>
  </p>
  </div>
</div> 
 <% end %>